application: pip_tkinter_backend
version: 0-1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.(html|js|css|json|png|woff|woff2|ttf))$
  static_files: static/docs/\1
  upload: static/.*\.(html|js|css|json|png|woff|woff2|ttf)$

- url: /docs
  static_files: static/docs/index.html
  upload: static/index.html
  mime_type: text/html

- url: .*
  script: main.application

libraries:
- name: webapp2
  version: "2.5.2"
- name: lxml
  version: "latest"
- name: ssl
  version: latest

builtins:
- remote_api: on
- appstats: off
